--WHERE ATT > (SELECT FROM WHERE); SCALA RETURN
--WHERE ATT IN (SELECT FROM WHERE); A SET OF TUPLES RETURN
--WHERE ATT ALL(SELECT FROM WHERE);
--WHERE ATT ANY(SELECT FROM WHERE); 
--WHERE ATT NOT EXIST(SELECT FROM WHERE); RETURN하면 FALSE, RETURN이 없으면 TRUE

--WHERE 조건절은 TRUE OR FALSE임
--CORELATION : 외부투플이 변함에 따라 IN A QUERY 가 변하면 상관관계가 있는 것
--WHERE NOT EXIST(S1 MINUS S2); 외부 투플의 변동에 따라 TRUE, FALSE여부가 결정된다.


--JOHN SMITH가 수행하는 프로젝트 넘버를 검색하라.
SELECT PNO
FROM EMPLOYEE, WORKS_ON
WHERE SSN = ESSN AND UPPER(FNAME) = 'JOHN' AND UPPER(LNAME) = 'SMITH';





--JHON SMITH가 수행하는 프로젝트를 수행하는 직원의 FNAME, LNAME을 검색하라.
SELECT FNAME, LNAME
FROM EMPLOYEE, WORKS_ON
WHERE SSN = ESSN
AND PNO IN (SELECT PNO
FROM EMPLOYEE, WORKS_ON
WHERE SSN = ESSN AND UPPER(FNAME) = 'JOHN' AND UPPER(LNAME) = 'SMITH' 
);--항상 1,2 만 리턴하므로 CORELATION이 없음


--JHON SMITH가 수행하는 프로젝트를 모두 수행하는 직원의 FNAME, LNAME을 검색하라.
--'모두'가 들어가면 WHERE NOT EXIST 쓸 생각하자.
--2중 FOR문과 유사

WHERE NOT EXISTS (
    (SELECT PNO
FROM EMPLOYEE, WORKS_ON
WHERE SSN = ESSN AND UPPER(FNAME) = 'JOHN' AND UPPER(LNAME) = 'SMITH') -- JOHN SMITH가 하는 프로젝트
    MINUS
    (SELECT PNO
    FROM WORKS_ON
    WHERE E.SSN = ESSN) -- EACH EMPLOYEE가 수행하는 프로젝트
);

--6번부서가 담당하는 프로젝트를 수행하는 사원의 이름을 검색하라.
SELECT FNAME, LNAME
FROM EMPLOYEE, PROJECT, WORKS_ON
WHERE PNO = PNUMBER AND ESSN = SSN AND DNO = 6;

--6번부서가 담당하는 프로젝트를 모두 수행하는 사원의 이름을 검색하라
SELECT FNAME, LNAME
FROM EMPLOYEE E
WHERE NOT EXISTS(
    (SELECT PNUMBER
FROM EMPLOYEE, PROJECT
WHERE DNUM = 6) -- 6번부서가 담당하는PROJECT NUMBER
    MINUS
    (SELECT PNO
    FROM WORKS_ON
    WHERE E.SSN = ESSN) -- 각 사원이 담당하는 PROJECT NUMBER
);


--6번부서가 담당하는 프로젝트 NUMBER를 검색하라.
SELECT PNUMBER, PNAME
FROM PROJECT
WHERE DNUM = 6;




--10번, 29번, 스스로 하는 질의가 숙제임
--6.123은 설렁설렁 6.45는 완전히 읽어야 한다.
