--장르가 '다큐멘터리'인 비디오 테이프를 예약한 고객의 이름을 검색4
SELECT NAME
FROM CUSTOMER C, RESERVED R, VIDEO V
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID AND R.VIDEO_ID = V.VIDEO_ID
    AND GENRE  = '다큐멘터리';


--장르가 '다큐멘터리'인 비디오 테이프를 모두 예약한 고객의 이름을 검색
SELECT NAME
FROM CUSTOMER C
WHERE NOT EXISTS(
    (SELECT VIDEO_ID 
    FROM VIDEO
    WHERE UPPER(GENRE) = 'ACTION') -- 장르가 '다큐멘터리'인 VIDEO_ID (UNCORRELATED)
    MINUS
    (SELECT VIDEO_ID
    FROM RESERVED 
    WHERE CUSTOMER_ID = C.CUSTOMER_ID) -- EACH CUSTOMER가 RESERVED한 VIDEO_ID(CORRELATED)
)


